### ISSUE TITLE
ocr 报错

### ISSUE THREAD

**Issue by N3verL4nd** [hamibot/hamibot#45]
`auto.waitFor();
if (!requestScreenCapture()) {
  toastLog('没有授予 Hamibot 屏幕截图权限');
  hamibot.exit();
}
log('开始截屏');
const img = captureScreen();
toastLog('开始识别');
const res = ocr.recognize(img);
log(res);
hamibot.exit();`

执行 ocr demo 报错
![image](https://user-images.githubusercontent.com/11865760/164981949-bcf7b9c7-b137-443b-a3da-a05208cb2ed3.png)

**Comment by batu1579** [comment]
可能需要在更新一下软件版本

**Comment by batu1579** [comment]
可能需要在更新一下软件版本

**Comment by yangy996** [comment]
试试这个
https://blog.csdn.net/YY007H/article/details/124540297
