### ISSUE TITLE
请问控件操作  是否 对第三方软件应用分身无效

### ISSUE THREAD

**Issue by niusme** [hamibot/hamibot#55]
请问控件操作  是否 对第三方软件应用分身无效。
我用饿了么app抓取的相关信息写的脚本可以跑饿了么官方的app。但是无法操作使用第三方分身软件分身的饿了么应用

**Comment by niusme** [comment]
准确来说 应该是id选择器失效了

**Comment by batu1579** [comment]
有的软件的空间id是随机的，建议用相对定位来获取，比如有全局唯一的某控件，那就先获取这个离目标最近的，然后通过取子控件的方式找到目标的，方式多的很怎么最快怎么来吧。ps如果你写过css的话，这个想法和css选择器很像。
