### ISSUE TITLE
[BUG] 这不是套壳吗

### ISSUE THREAD

**Issue by Nobellcq** [hamibot/hamibot#71]
**错误描述**
清晰而简洁的描述一下遇到的 Bug 。

**错误复现**
产生 Bug 的代码或要复现 Bug 需要进行的操作（这有助于尽快定位问题）。

**行为预期**
清晰而简明的描述一下你期望这段代码或进行的操作产生的结果。

**截图**
如果可以的话，添加截图来帮助解释您遇到的问题。

**机器人型号（请填写以下信息）：**
 - 设备型号：[例如：红米 K40]
 - 操作系统：[例如：MIUI 12]
 - Hamibot 版本：[例如：1.2.0]

**其他说明**
任何有关该问题的其他说明。

**Comment by batu1579** [comment]
hamibot 提供了远程启动功能，和 autojs 还是有些差别的吧
