### ISSUE TITLE
[Issue] OpenCV 和 paddleocr 似乎放错了位置

### ISSUE THREAD

**Issue by Hunter-857** [hamibot/hamibot#78]
**错误描述**
/inrt/libs/opencv-4.2.0.aar
     Required by:
         project :inrt > project :autojs
似乎是这个文件找不到了。

**Comment by Ancleb** [comment]
解决了吗，我我也是这样的

**Comment by Hunter-857** [comment]
重新编译下 paddle ocr 就行了， 实在不行就先不用ocr ，把init ocr 注解了

**Comment by RandallXia** [comment]
我是把 paddle 的依赖取消了，并注释了paddle 相关的代码才编译成功的
