### ISSUE TITLE
如何能实现自动运行脚本

### ISSUE THREAD

**Issue by dundunnp** [hamibot/hamibot#9]
您好，我在实现一个微信健康打卡后，发现这完全不自动嘛:(，只是把打卡微信点击打卡的操作换成了打开hamibot的控制台点击运行脚本，这看起来这并没有更自动化，换汤不换药了。

**如何实现每天在某个时刻自动运行你的脚本（而不是自己手动点击运行）?**

_或许是我没仔细看完开发文档，求指教_
_另外你们的项目真的很不错，很多操作居然不用root权限，这对我这个鸿蒙无root权限用户也好了_

**Comment by xiaod945** [comment]
用api啊
https://docs.hamibot.com/rest/reference#%E8%BF%90%E8%A1%8C%E8%84%9A%E6%9C%AC
